### PR TITLE
Patch for issues 133 and 135

### LINKED ISSUE #133: Any reason SELECTing on a predicate wouldn't be working?
This seems so trivial I'm nervous to ask!  But I can't seem to get selecting via a predicate to work.

```
// Returns results
$q = 'PREFIX dcterms:  <http://purl.org/dc/terms/> .
  SELECT *
  WHERE {
    ?s ?p "34.145369444444,-118.40721111111" .
  }';
```

```
// Returns no results and no errors
$q = 'PREFIX dcterms:  <http://purl.org/dc/terms/> .
  SELECT *
  WHERE {
    ?s <http://purl.org/dc/terms/spatial> ?o .
  }';
```
```
// ... nor ...
$q = 'PREFIX dcterms:  <http://purl.org/dc/terms/> .
  SELECT *
  WHERE {
    ?s dcterms:spatial ?o .
  }';
```
```
// Also tried this just to be sure, returns no results or errors
$q = 'PREFIX dcterms:  <http://purl.org/dc/terms/> .
  SELECT *
  WHERE {
    ?s dcterms:spatial "34.145369444444,-118.40721111111" .
  }';
```

Thank you!

### LINKED ISSUE #135: fetchRow() returns false, not null, resulting in false positive for hasHashColumn()
(Submitting this sanity check before a pull request.)

We're working with some old ARC databases that we've upgraded the library for.  It seems that 'val_hash' has been added as a column to the s2val table, but in our old databases this column doesn't get added.  That said, there's a check for the existence of 'val_hash' in the core library:

https://github.com/semsol/arc2/blob/master/store/ARC2_Store.php#L189-L200

However, AFAICT, $this->db->fetchRow(...) returns false, not null, when it can't find the column. This results in a false positive because of this line which is looking for null:

```php
$this->$var_name = null !== $row;
```

On our installs I've changed that line to this, and it seems to get things working as expected:

```
 $this->$var_name = null;
 if ($row) $this->$var_name = true;
```

Thanks for taking a look at this!

---
**EDIT by @k00ni**: Added code highlighting.

### PR DESCRIPTION
**Pull request by k00ni**
This pull request is fully based on the work of @craigdietrich.

* Fixes #133
* Fixes #135

### CODE REVIEW

**Comment by k00ni** [comment]
@craigdietrich, your changes seem to fail if `mysqli` is in use. With `pdo` adapter everything seems fine. 

Example: https://travis-ci.org/semsol/arc2/jobs/657335341#L386

Any idea?

**Comment by craigdietrich** [comment]
Here is the way we've always hooked up, based on the ARC2 documentation:

```
$config = array(
  'db_host' => $hostname,
  'db_port' => $ci->db->port,
  'db_name' => $ci->db->database,
  'db_user' => $ci->db->username,
  'db_pwd'  => $ci->db->password,
  'store_name' => rtrim($ci->db->ARC_dbprefix, '_'),
);
$this->store =@ ARC2::getStore($config);
// $this->store->createDBCon();
if (!$this->store->isSetUp()) $this->store->setUp();
$this->ns = $ci->config->item('namespaces');
```

Is there a separate way to enable mysqli?

**Comment by k00ni** [comment]
You already using `mysqli`, because its the default setting. It can be forced though by:

```php
$config['db_adapter'] = 'mysql';
```

**Comment by k00ni** [comment]
@craigdietrich: Can you please fix the code, which breaks tests in `mysqli`?

**Comment by craigdietrich** [comment]
@k00ni I'm not familiar with Travis, though not sure what to change in general.  Only a couple lines were updated, and one of them is a simple change to "if (1)" .. the other removing "$row == null" to "!$row"... meaning, I'm not sure how these would impact a Travis compile task.

Could someone help me out?  -- thanks!

**Comment by craigdietrich** [comment]
I noticed that if the ARC tables are fresh (ie, have no data in them yet), if a predicate is asked for (SELECT) that has a question mark ("?") in the object, then this line in the 'joshcam' mysqli adapter throws a warning, because "$vals[2]" doesn't exist:

$val = $vals[$i++];

in

```
    protected function replacePlaceHolders($str, $vals)
    {
        $i = 1;
        $newStr = "";

        if (empty($vals)) {
            return $str;
        }

        while ($pos = strpos($str, "?")) {
            $val = $vals[$i++];
            if (is_object($val)) {
                $val = '[object]';
            }
            if ($val === null) {
                $val = 'NULL';
            }
            $newStr .= substr($str, 0, $pos) . "'" . $val . "'";
            $str = substr($str, $pos + 1);
        }
        $newStr .= $str;
        return $newStr;
    }
```

My changes allow queries through to id2val that it didn't before... not sure how this would relate to o2val, but the warning didn't exist before my changes went live.  :/

**Comment by craigdietrich** [comment]
I think one think that would be helpful is for other(s) to check to see if their id2val tables are overrun with duplicate entries?  (E.g., thousands of rows instead of dozens, depending on the ontologies being used.)   MySQL versions and such could be in play but I hope I'm not the only one seeing the problem (in which case I need to get my eyes checked!).

Thanks!

**Comment by k00ni** [comment]
Which way do we go from here?

For me there are the following options:

1. One has time to hunt down the bug, which causes this buggy behavior. A fix can be merged in, if all tests run without errors.
2. We document all we have in the related issue(s) #133 resp. #135 and close this pull request for as long as there is no fix.

I won't merge in code which breaks our tests.

**Comment by craigdietrich** [comment]
#2 makes sense, of course.  Fortunate that nobody else is experience the is2val overrun!

**Comment by k00ni** [comment]
Closed for now until we got a fix, which doesn't break our tests. 

@craigdietrich Thank you for your efforts anyway.

**Pull request closed without merging**
