### PR TITLE
Fixed severe bugs

### PR DESCRIPTION
**Pull request by Knurg**
Fixed the severe bugs stated at https://github.com/semsol/arc2/issues/8 and https://github.com/semsol/arc2/pull/5

### CODE REVIEW

**Comment by k00ni** [comment]
Is there a chance that this pull gets commited in the near future?

**Comment by bnowack** [comment]
There are conflicts, the PR can't be auto-merged, unfortunately.

**Comment by k00ni** [comment]
Hi @Knurg, would you mind trying to adapt your files so that we can merge them? Thank you.

**Comment by Knurg** [comment]
I'm sorry, but I don't use arc2 anymore - so I can't test it :(

**Comment by k00ni** [comment]
> I'm sorry, but I don't use arc2 anymore - so I can't test it :(

No problem. 

One may cherry pick parts of this pull, but i would like to close this pull for now. Ok?

**Comment by Knurg** [comment]
Yes 👍

**Pull request closed without merging**
