### PR TITLE
Fixing failing tests (issue #125)

### PR DESCRIPTION
**Pull request by cbinding**
Fix for failing tests as they were either making incorrect assertions or attempting to load data files that do not exist

### CODE REVIEW

**Comment by k00ni** [comment]
Hi @cbinding, big thank you! 

Unfortunately, 1 test still fails: 

https://travis-ci.org/semsol/arc2/jobs/484310143#L687

Any idea?

**Comment by k00ni** [comment]
I read the related issue #125.

You wrote:

> Hi Konrad, thanks for following up - looking at one example https://github.com/semsol/arc2/blob/master/tests/db_adapter_depended/store/ARC2_StoreTest.php test 'testMultipleInsertQuerysInDifferentGraphs' which is currently failing - the assertion in the test itself appears to be incorrect. It inserts 1 triple into graph1 and 2 triples into graph2 but then asserts there should now be 1 triple in each graph - this test will always fail.

If that is the case, could you please remove it then?

**Comment by cbinding** [comment]
Hi, I believe this fixed test is now 'correctly' failing - i.e. it is correctly flagging up the insert problem as described in your issue #114 test code. The fix in pull request #123 should resolve this

**Comment by k00ni** [comment]
I merged your PRs. Lets see what Travis has to say after all tests ran. :)

**Comment by k00ni** [comment]
Something went wrong i guess. There different errors in different environments now. For instance, MySQL 5.5 + PHP 7 + mysqli: https://travis-ci.org/semsol/arc2/jobs/484344747#L681. Fewer errors when using PDO: https://travis-ci.org/semsol/arc2/jobs/484344748#L673.

Any idea?

**Comment by cbinding** [comment]
The new PDO errors seem to be lower level SQL escaping issues connected with the content of the particular Turtle test file being loaded. However - the test file being loaded now is NOT the same file originally used, as the triple count is now different (was 106, now 1860). Sorry this was my error - I think the 'original' test file is actually located at https://raw.githubusercontent.com/semsol/arc2/master/tests/db_adapter_depended/sparql_1_1_tests/w3c-tests/move/manifest.ttl - I will amend the test code accordingly. 

As for the mysqli errors,unfortunately I don't have an answer there at the moment.

**Comment by cbinding** [comment]
OK, interesting result after maling that change - tests using PDO now all pass; tests using mysqli all still fail. The errors seem to be in the sparql 1.1 compliance tests

**Comment by k00ni** [comment]
The current situation is very unfortunate and i tend to revert all the changes. Let's see, maybe later we can locate the problem.

Fixes some of the errors: #127

**Comment by k00ni** [comment]
Superseded by #137, please open if there is still something to discuss.

**Pull request merged**
