### PR TITLE
Attempt to implement an in-memory store using SQLite

### PR DESCRIPTION
**Pull request by k00ni**
### What?

This PR contains code for an in-memory store which uses PDO + SQLite (`:memory:`). Because it is based on existing classes it provides the same functionality as its MySQL based pendant.

I also extended PHP-CS-Fixer coverage and improved code readability overall.

### Details 

* `PDOAdapter` class got another check to make sure it is only used with `mysql` protocol.
* Adapted classes like `ARC2_Store` to distinguish between MySQL and SQLite approaches
* `ARC2_StoreLoadQueryHandler::checkSQLBuffers`: **removed** fourth parameter, because it is unused inside the function
* `ARC2_StoreSelectQueryHandler::getTempTableDef`: **renamed** it to `getTempTableDefForMySQL` and added a second version for SQLite (called `getTempTableDefForSQLite`)
* **reworked Github Actions**  to test the library (focused on simplifications and clear code)
* **fixed coding styles** in further files to improve code readability
* removed further instances of the **error control operator** `@`, e.g. `@include_once` (suppressing errors is bad coding style because you might not see when something went wrong)
* improved **README.md** (shows test cases, added in-memory example)
* added test coverage for **MySQL 5.5**

Ref: #105

### CODE REVIEW

**Comment by k00ni** [comment]
We have an in-memory store now! :rocket:

Added a small section to README.md about the new store: https://github.com/semsol/arc2/tree/pr/sqlite-in-memory-store#in-memory-store-sqlite-based

@semsol (@bnowack): What do you think? I know there are many changes, but if you could take a look at SQLite related changes in `store/`. My approach was to keep what you've built and add some `if-clauses`, in case SQL differs between MySQL and SQLite. Thanks in advance.

**Comment by k00ni** [comment]
@zozlak: What do you think about a standalone library providing an in-memory triple store? It could be based on this code here, using SQLite with `:memory:`.

**Comment by zozlak** [comment]
> What do you think about a standalone library providing an in-memory triple store? It could be based on this code here, using SQLite with :memory:.

I think there are many things to discuss here but I would be glad to talk with you about it. I propose you contact me by [email](mailto:zozlak@zozlak.org) not to spam here too much.

**Comment by bnowack** [comment]
Wow! how cool is that?

**Pull request merged**
