### PR TITLE
refector: Drop usage of xml_set_object()

### PR DESCRIPTION
**Pull request by Girgias**
Use proper callables instead.

Related to: https://github.com/php/php-src/pull/12340

### CODE REVIEW

**Comment by Girgias** [comment]
PHP_CS_FIXER warning is unrelated to this PR and a pre-existing issue.

**Comment by k00ni** [comment]
Thank you @Girgias. I am super busy currently, but I will look into that soonish. PR looks good at first glance, but I may have to fix our CI because only coding style check ran.

**Review by k00ni — APPROVED** [review]

**Comment by k00ni** [comment]
Thank you @Girgias

**Comment by Girgias** [comment]
Glad to help :D

**Pull request merged**
